apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: probelet
  name: probelet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probelet
  template:
    metadata:
      labels:
        app: probelet
    spec:
      containers:
        - image: ghcr.io/alkindi42/probelet:latest
          name: probelet
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
      terminationGracePeriodSeconds: 5
