apiVersion: v1
kind: Service
metadata:
  name: probelet
  labels:
    app: probelet
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  type: ClusterIP
  selector:
    app: probelet
